### ISSUE TITLE
Test of new Epson integration

### ISSUE THREAD

**Issue by pszafer** [pszafer/epson_projector#7]
@Icexist can you test new integration -> this branch https://github.com/pszafer/core/tree/epson_integration

**Comment by Icexist** [comment]
Thanks for your work on this!

I tried the new integration by downloading it and replacing it in the `/components/` directory. It appears it downloaded the `epson_projector` version 0.2.1 but it didn't work. I didn't notice any errors, but there was also no `media_player` component available for epson. 

Do I need to change my configuration.yaml file? Or should I install it some other way?

HA version 0.113.3, running on HASSIO.

Config.yaml

```yaml
media_player:
  - platform: epson
    host: ip.ad.dr.ess
    name: 'Epson Projector'
```

Logs for loading HA:

```text
2020-08-26 16:27:20 INFO (SyncWorker_2) [homeassistant.loader] Loaded epson from homeassistant.components.epson
2020-08-26 16:27:22 INFO (MainThread) [homeassistant.setup] Setting up epson
2020-08-26 16:27:22 INFO (MainThread) [homeassistant.setup] Setup of domain epson took 0.4 seconds
2020-08-26 16:27:23 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.epson
```

This is what I got when changing the CMODE:

```text
2020-08-26 16:39:01 INFO (MainThread) [homeassistant.components.automation] Executing Color Mode
2020-08-26 16:39:01 INFO (MainThread) [homeassistant.components.automation] Color Mode: Running script
2020-08-26 16:39:01 INFO (MainThread) [homeassistant.components.automation] Color Mode: Executing step call service
2020-08-26 16:39:01 ERROR (MainThread) [homeassistant.components.automation] Color Mode: Error executing script. Service not found for call_service at pos 1: Unable to find service epson/select_cmode
2020-08-26 16:39:01 ERROR (MainThread) [homeassistant.components.automation] While executing automation automation.color_mode
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 409, in async_trigger
    await self.action_script.async_run(variables, trigger_context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 790, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 185, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 193, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 382, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1231, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service epson/select_cmode
```

**Comment by Icexist** [comment]
As another note, here are all the epson log lines from my startup of HA with 0.113.3 on HassIO with the old (current released) integration, epson_projector 0.1.3, and my added `'PWR': 10` timeout.

```text
2020-08-26 16:54:43 INFO (SyncWorker_4) [homeassistant.loader] Loaded epson from homeassistant.components.epson
2020-08-26 16:54:45 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.epson
2020-08-26 16:54:46 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:54:48 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:54:59 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:54:59 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:55:09 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:55:09 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:55:19 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:55:19 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:55:29 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:55:29 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:55:39 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:55:39 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:55:49 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:55:49 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:55:59 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:55:59 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:56:09 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:56:09 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:56:19 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:56:19 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:56:29 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:56:29 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:56:39 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:56:39 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:56:49 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:56:49 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:56:59 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:56:59 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:57:09 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:57:09 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:57:19 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:57:19 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04
2020-08-26 16:57:29 DEBUG (MainThread) [epson_projector.main] Getting property PWR
2020-08-26 16:57:29 DEBUG (MainThread) [homeassistant.components.epson.media_player] Project turn on/off status: 04


```

**Comment by pszafer** [comment]
remove config from configuration.yaml and try to add it with integration menu.

Also you can just download epson directory from this branch and just put it in custom_component dir.

**Comment by Icexist** [comment]
Ok!

Added `epson` to the `custom_component` dir and removed the `media_player` config. It didn't show up in the integrations list in the UI, so I tried both adding "epson" directly to `config_flows.py` and running `python3 -m script.hassfest` and neither worked. I then removed `epson` from `custom_components` and added it directly to `/components/` and re-ran `script.hassfest`. 

Epson doesn't show in the integration list in the UI, but the log shows:

```text
2020-08-26 17:46:04 INFO (SyncWorker_6) [homeassistant.loader] Loaded epson from homeassistant.components.epson
```

I think I'm missing something?

**Comment by pszafer** [comment]
Follow instruction below:

```
git clone https://github.com/pszafer/core.git --branch epson_integration --single-branch epson_core
cd epson_core
python -m venv venv
source venv/bin/activate
script/setup
hass -c config
```

now go to http://localhost:8123 and in integration you should see epson as below:


![image](https://user-images.githubusercontent.com/690510/91339541-ed641c00-e7d6-11ea-91c8-a39375fa71d5.png)

**Comment by Icexist** [comment]
Thanks for your patience with me! This worked just fine on a dev box. I was able to add the projector.

Things I noticed:
- Power on/off worked great
- Changing the CMODE worked from the service screen
- Changing input source didn't work from the lovelace card but worked when calling the service directly.
- This is what I saw when the flow was started: 
  
![image](https://user-images.githubusercontent.com/5529540/91343370-4e690100-e791-11ea-8854-96152a5dd616.png)


Now that I've got this up and running, let me know if there's anything else you'd like me to test!

**Comment by pszafer** [comment]
you can go to integration options there and check out timeout factor. You can put eg 1.5 and it will multiply timeout eg for PWR 40x1.5=60.

**Comment by Icexist** [comment]
Awesome. I didn't need to do that with the new integration, but I tested it.

Any number that ends with a 0 fails with "User Input Malformed" so since I changed from 1 to 1.5, I can't switch it back to 1.

- 1.00001 works
- 1.0 does not work
- 1 does not work
- 10001 works
- 100 does not work
- 0 does not work

**Comment by pszafer** [comment]
can you check now new version?

inside core dir:
```
git pull
```

**Comment by Icexist** [comment]
Switching sources from the Lovelace card still doesn't work.

Setting the number in the option to 1, 1.0, 100 all can be set. 0 also works. I don't think that 0 should be able to be set?

0 definitely works and causes the timeout error to reappear.

**Comment by pszafer** [comment]
> Switching sources from the Lovelace card still doesn't work.

I'll check it.

> 
> Setting the number in the option to 1, 1.0, 100 all can be set. 0 also works. I don't think that 0 should be able to be set?
> 
> 0 definitely works and causes the timeout error to reappear.

This should be fixed. Minimum is 1 one.

**Comment by pszafer** [comment]
Little updae about switching sources. I don't know why it is not working, I'll try to ask somebody from HA frontend dev team

**Comment by Icexist** [comment]
Switching sources isn't a problem for me personally as I don't switch sources using the projector but I'm willing and able to help test as necessary. Just let me know what you need!

**Comment by pszafer** [comment]
We need to wait for new version of https://pypi.org/project/home-assistant-frontend/
it should be available within a few days.

**Comment by pszafer** [comment]
@Icexist I pushed some fixes. Sources should be switchable now.
Can you check if it's working? Same instructions as before.

**Comment by Icexist** [comment]
Just tried it and switching sources from the lovelace card works!

**Comment by pszafer** [comment]
cool, I'll prepare PR than and push it to HA Core next week

**Comment by pszafer** [comment]
little update for anybody who land here.
I made PR: https://github.com/home-assistant/core/pull/39697 and it's currently waiting for somebody to review or merge.
